import { POI } from '@models';

const pois: POI[] = [
  {
    id: 'oysho_madrid_granVia33',
    lat: 40.4200673,
    lng: -3.7041583,
    type: 'store',
    label: 'Oysho Madrid Gran Vía 33',
  },
  {
    id: 'oysho_barcelona_passeigDeGracia13',
    lat: 41.391,
    lng: 2.162,
    type: 'store',
    label: 'Oysho Barcelona Passeig de Gracia 13',
  },
  {
    id: 'oysho_barcelona_pelai40',
    lat: 41.382,
    lng: 2.171,
    type: 'store',
    label: 'Oysho Barcelona Pelai 40',
  },
  {
    id: 'oysho_madrid_hermosilla16',
    lat: 40.420124,
    lng: -3.7040823,
    type: 'store',
    label: 'Oysho Madrid Hermosilla 16',
  },
  {
    id: 'oysho_madrid_goya65',
    lat: 40.423,
    lng: -3.683,
    type: 'store',
    label: 'Oysho Madrid Goya 65',
  },
  {
    id: 'oysho_valencia_colon10',
    lat: 39.4699,
    lng: -0.3763,
    type: 'store',
    label: 'Oysho Valencia Colón 10',
  },
  {
    id: 'oysho_bilbao_granvia31',
    lat: 43.263,
    lng: -2.935,
    type: 'store',
    label: 'Oysho Bilbao Gran Vía 31',
  },
  {
    id: 'oysho_sevilla_luisDeMorales3',
    lat: 37.389,
    lng: -5.984,
    type: 'store',
    label: 'Oysho Sevilla Luis de Morales 3',
  },
  {
    id: 'oysho_aCoruna_plazaDeLugo14',
    lat: 43.3623,
    lng: -8.4115,
    type: 'store',
    label: 'Oysho A Coruña Plaza de Lugo 14',
  },
  {
    id: 'oysho_valladolid_calleSantiago25',
    lat: 41.652,
    lng: -4.7245,
    type: 'store',
    label: 'Oysho Valladolid Calle Santiago 25',
  },
  {
    id: 'drop_rocaMadrid_parqueSur',
    lat: 40.3333,
    lng: -3.701,
    type: 'dropPoint',
    label: 'Drop Point Roca Madrid Parque Sur',
  },
  {
    id: 'drop_cc_nouCentro_valencia',
    lat: 39.481,
    lng: -0.395,
    type: 'dropPoint',
    label: 'Drop Point CC Nou Centro Valencia',
  },
  {
    id: 'drop_cc_lagoh_sevilla',
    lat: 37.388,
    lng: -5.995,
    type: 'dropPoint',
    label: 'Drop Point CC Lagoh Sevilla',
  },
  {
    id: 'drop_cc_europa_barcelona',
    lat: 41.405,
    lng: 2.191,
    type: 'dropPoint',
    label: 'Drop Point CC Europa Barcelona',
  },
  {
    id: 'drop_cc_artea_parque_bilbao',
    lat: 43.262,
    lng: -2.923,
    type: 'dropPoint',
    label: 'Drop Point CC Artea Parque Bilbao',
  },
];

export { pois };
